name: Deploy Get Smart Infra

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Terraform Apply (Get Smart)
    runs-on: ubuntu-latest

    permissions:
      id-token: write        # Required for GitHub OIDC â†’ TFC
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # Point Terraform to the get-smart directory
      - name: Terraform Init
        working-directory: infra/prod/get-smart
        run: terraform init -input=false

      - name: Terraform Plan
        working-directory: infra/prod/get-smart
        run: terraform plan -input=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: infra/prod/get-smart
        run: terraform apply -auto-approve -input=false
