name: Deploy Get Smart Infra

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Terraform Apply (Get Smart)
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      TF_CLOUD_ORGANIZATION: justinklein
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      TF_CLOUD_WORKSPACE: prod-get-smart

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        working-directory: infra/prod/get-smart
        run: terraform init -input=false

      - name: Terraform Plan (remote)
        working-directory: infra/prod/get-smart
        run: terraform plan -input=false -no-color

      - name: Terraform Apply (remote)
        if: github.ref == 'refs/heads/main'
        working-directory: infra/prod/get-smart
        run: terraform apply -auto-approve -input=false -no-color
